monitoring_pve_exporter_enabled: true

monitoring_proxmox_targets:
  - "192.168.1.67"

monitoring_proxmox_cluster_enabled: false
monitoring_proxmox_node_enabled: true

monitoring_proxmox_api_user: "monitoring@pve"
monitoring_proxmox_api_token_name: "prometheus"
monitoring_proxmox_api_token_value: "{{ vault_monitoring_proxmox_api_token_value }}"
monitoring_proxmox_verify_ssl: false