---
- name: Ensure Proxmox exporter directory exists
  ansible.builtin.file:
    path: "{{ monitoring_stack_install_dir }}/pve-exporter"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy Proxmox exporter config
  ansible.builtin.template:
    src: pve.yml.j2
    dest: "{{ monitoring_stack_install_dir }}/pve-exporter/pve.yml"
    owner: root
    group: root
    mode: "0644"
  notify: Restart monitoring stack
